baseurl = "//qinghaoliang.github.io/"
DefaultContentLanguage = "en"
title = "Qinghao Liang"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = '''
                I'm Qinghao Liang, a PhD candidate in Biomedical Engineering at Yale University, 
                with a focus on machine learning in Neuroimaging. 
                My research aims to enhance data imputation and transfer learning for better prediction in brain connectomes, 
                striving to conserve neuroimaging data and boost prediction accuracy. I previously
                completed my BS in Physics at University of Science and Technology of China. 
              '''
  mainSections = ["post","posts"]
  logo = "img/profile.png" # Expecting square dimensions
  favicon = "img/brain.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[[Params.bigimg]]
  src = "img/sphere.jpg"
  position = "top"
  
[Author]
  name = "Qinghao Liang"
  email = "qinghao.liang@yale.edu"
  github = "qinghaoliang"
  twitter = "liang_qinghao"
  linkedin = "qinghao"
  #instagram = "qinghaoliang"

[[menu.main]]
    parent = "Projects"
    name = "Resolving Atlas Divergence in Connectomes"
    url = "projects/connectome_transformation"
    weight = 1

[[menu.main]]
    parent = "Projects"
    name = "Rescuing missing data"
    url = "projects/missing_data"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Learning across atlases"
    url = "projects/learning_across_atlases"
    weight = 3

[[menu.main]]
    name = "Resume"
    url = "resume/Qinghao_resume.pdf"
    weight = 2

[[menu.main]]
    identifier = "Publications"
    url = "https://scholar.google.com/citations?user=jwf6KUEAAAAJ&hl=en"
    name = "Publications"
    weight = 3



